### ISSUE TITLE
Unable to see the imports

### ISSUE THREAD

**Issue by tazV2** [abbas455/Coursera_Capstone#1]
Hello @abbas455 ,
I am unable to see the pandas and numpy imports. 
That is why I am not marking your assignment. Please fix it. 
Thank you,
Taz

**Comment by abbas455** [comment]
its look like technical fault.i checked it. don't know why

> Hello @abbas455 ,
> I am unable to see the pandas and numpy imports.
> That is why I am not marking your assignment. Please fix it.
> Thank you,
> Taz

its look like technical fault.i checked it. don't know why
